---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

version: "3.9"
services:

  db:
    image: "postgres:13.10-alpine"
    container_name: pysect-backend-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pysect-network
    ports:
      - "9001:5432"
    env_file:
      - ./docker/config/.env

  redis:
    image: redis:latest
    container_name: pysect-backend-redis
    ports:
      - "9002:6379"
    networks:
      - pysect-network

  web:
    image: "pysect-backend:dev"
    container_name: pysect-backend-web
    ports:
      - "9000:8000"
    #platform: linux/amd64
    build:
      target: builder_image
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: development
        # See: https://github.com/wemake-services/wemake-django-template/issues/1518
        USER_ID: ${UID:-1000}
        USER_GID: ${GID:-1000}
      cache_from:
        - "pysect-backend:dev"
        - "pysect-backend:latest"
        - "*"
    volumes:
      - django-static:/var/www/django/static
      - django-logs:/var/www/log
      # We should only mount source code in development:
      - .:/code
    depends_on:
      - db
    networks:
      - pysect-network
    env_file:
      - ./docker/config/.env
    command: ./docker/django/local_run.sh

networks:
  # Network for your internals, use it by default:
  pysect-network:
    external: true


volumes:
  pgdata:
  django-static:
  django-logs:
