---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

version: "3.6"
services:
  rabbit:
    image: rabbitmq
    container_name: pysect-rabbit
    ports:
      - "5672:5672"
    networks:
      - webnet

  db:
    image: "postgres:13.10-alpine"
    container_name: pysect-backend-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    ports:
      # We only bind ports directly in development
      - "9001:5432"
    env_file:
      - ./docker/config/.env

  web:
    image: "pysect-backend-backend:dev"
    container_name: pysect-backend-web
    privileged: true
    ports:
      # We only bind ports directly in development:
      - "9000:8000"
    platform: linux/x86_64
    build:
      target: builder_image
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: development
        # See: https://github.com/wemake-services/wemake-django-template/issues/1518
        USER_ID: ${UID:-1000}
        USER_GID: ${GID:-1000}
      cache_from:
        - "pysect-backend-backend:dev"
        - "pysect-backend-backend:latest"
        - "*"

    volumes:
      - django-static:/var/www/django/static
      # We only mount source code in development:
      - .:/code
    depends_on:
      - db
      - rabbit
    networks:
      - webnet
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./docker/config/.env
    environment:
      DJANGO_DATABASE_HOST: db
    command: dockerd && ./docker/django/local_run.sh

    # This task is an example of how to extend existing ones:
    #   some_worker:
    #     <<: *web
    #     command: python manage.py worker_process

networks:
  # Network for your internals, use it by default:
  webnet:


volumes:
  pgdata:
  django-static:


